export interface Ordenservicio {
    id:number;
    cliente:number;
    fecha_recepcion: Date;
    fecha_entrega: Date;
    estado:number;
    responsable:string;
    observaciones:string;
    tipoobjeto:number;
    tecnico:string;
    marca:number;
    servicio:string;
    color:number;
    modelo:string;
    serie:string;
    calibre:string;
    maquina:string;
    metal:string;
    pulsera:number;
    ubicacion:number;
    eslabones:number;
    bisel:string;
    vidrio:string;
    esfera:string;
    agujas:string;
    corona:string;
    tamano:number;
    categoria:number;
    tienda:number;
    firma:any;
    eliminado:number;
    nombrefirma:string;
    material:number;
    broche:string;
    doblebroche:string;
    extension:string;
    hebilla:string;
    terminal:string;
    biselinterno:string;
    caja:string;
    cristal:string;
    protectorcorona:string;
    valvula:string;
    pulsador:string;
    fondo:string;
    nofondo:string;
    grabado:string;
    coloarmaquina:string;
    garantia:string; 
    pendulo:string;
    pesas:string;
    cadenas:string;
    llave:string;
    adornos:string;
    puerta:string;
    argolla:string;
    bateria:string;
    palanca:string;
    nomaquina:string;
    colormaquina:string;
    funcionando:number;
    movimiento:number;
    especialidad:number;
    tapa:string;
    bases:string;
    almohadilla:string;
    tapiceria:string;
    transformador:string;
    tapongas:string;
    cuerpo:string;
    clip:string;
    baseplumin:string;
    plumin:string;
    mina:string;
    tinta:string;
    tapon:string;
    nomodelo:string;
    

    posicion1:number;
    linea1:number;
    oh1:number;
    amplitud1:number;
    posicion2:number;
    linea2:number;
    oh2:number;
    amplitud2:number;
    posicion3:number;
    linea3:number;
    oh3:number;
    amplitud3:number;
    posicion4:number;
    linea4:number;
    oh4:number;
    amplitud4:number;
    posicion5:number;
    linea5:number;
    oh5:number;
    amplitud5:number;
    posicion6:number;
    linea6:number;
    oh6:number;
    amplitud6:number;
    posicion7:number;
    linea7:number;
    oh7:number;
    amplitud7:number;
    posicion8:number;
    linea8:number;
    oh8:number;
    amplitud8:number;
    posicion9:number;
    linea9:number;
    oh9:number;
    amplitud9:number;
    posicion10:number;
    linea10:number;
    oh10:number;
    amplitud10:number;
    promedio1:number;
    texto1:'';
    promedio2:number;
    texto2:''
    fecha            : Date;
    fecha2           : Date;
    fecha3           : Date; 
    fecha4           : Date; 
    hora             : Date;
    hora2            : Date;
    hora3            : Date; 
    hora4            : Date; 
    posicion         : number;
    posicion_2       : number;
    posicion_3       : number; 
    posicion_4       : number; 
    texto3           : string; 
    texto4            : string; 
    texto5            : string; 
    texto6            : string;
    promedio          : number;
    promedio_1        : number;
    idservicio        : number;
    observacioneservicio : string;
    fechaactualizoservicio: Date;
    usractualizoservicio:   string;
    impermiable : string;
    totalquetzales:0
    impuestos:0
    totalquetzalesimp:0
    totaldolares:0
    valorcomision:0
    totalpresupuesto:0
   }
